### ISSUE TITLE
Object point not sorted by slice number

### ISSUE THREAD

**Issue by AjitRanganath** [cortex-lab/allenCCF#23]
When I use Analyze_Clicked_Points to extract the marked probe points, the brain regions marked by the probe points are not sorted by the respective slices they were marked in; instead they are lumped by the probe number/color that was used. It would be useful to have the probe points sorted by the slices they were marked in.

Thanks!

**Comment by philshams** [comment]
In the Analyze_Clicked_Points.m file, the following line selects all the points from the probe number/color that was used: 
```
% get the object points for the currently analyzed object    
curr_objectPoints = objectPoints.pointList.pointList{selected_object,1}(:, [3 2 1]);
```
Instead, the name of the slice where a each point was clicked (for a particular probe) can be extracted as follows:
`slice_identities = objectPoints.pointList.pointList{selected_object,3}`

Alternatively, a cell array with the names of the slices for each probe can be extracted with:
`slice_identities = objectPoints.pointList.pointList(:,3)`

These could be used to sort probe points by slice. For example, you could assign an index to each unique slice name, and assign the point coordinates accordingly, in a new array. The point coordinates can be extracted with `objectPoints.pointList.pointList{probe_index,1}(slice_index, [3 2 1])`.Then instead of looping through objects in `for object_num = objects`, you could loop through slices.
