### ISSUE TITLE
Increase angle left right in allen_cf_npx

### ISSUE THREAD

**Issue by RobertoDF** [cortex-lab/allenCCF#42]
Hi,

While it is possible to change the angle of the probe using "up" and "down" arrow, the "left" and "right" don't work properly. If you change both sequentially the result is quite unpredictable.

**Comment by petersaj** [comment]
thanks for the catch - should be fixed now

**Comment by RobertoDF** [comment]
Hi! Tried the new commit but I can't tilt the probe left and right.

**Comment by petersaj** [comment]
hm it works on my machine - does that mean the shift+left/right now does nothing on yours? or what exactly?

**Comment by RobertoDF** [comment]
Yes, just tried on a different machine and also there I can't tilt the probe left and right. Shift+up/down work as expected.
Fundamentally it is the same as before even with the added `guidata(probe_atlas_gui, gui_data)`.
If I tilt the probe left (shift+left) nothing happens , however, if later I tilt it up (shift+up) it moves both left and up. The left/right angle movement seems dependent on the up/down. Hope it is clear!

**Comment by petersaj** [comment]
works on 2 computers over here - is it possible it's just moving small amounts but it's clearer if you hold the button down? I just added another commit, maybe pull and try again? 

the issue was that it wasn't uploading the new angle to the gui until after trying to change the angle, so the key presses lagged by 1, which those guidata commands fixed

**Comment by RobertoDF** [comment]
I pulled the commit, you can see it in my fork too. I really don't get what's wrong.
You can see in the first image it should be 45° from midline
![Screen Shot 2020-10-07 at 15 16 09](https://user-images.githubusercontent.com/37729096/95336025-6d8aa080-08b0-11eb-9cc9-88b2d3f18e9c.png)

if I move the horizontal axis however it also moves the midline
![Screen Shot 2020-10-07 at 15 16 26](https://user-images.githubusercontent.com/37729096/95336026-6fecfa80-08b0-11eb-9fc9-cc739213a7d3.png)

**Comment by petersaj** [comment]
That's intentional - in your first image, the probe is straight down (90 from horizontal), so rotating around the A-P axis just spins it around it's center. In your second image, you're now changing the horizontal rotation while the A-P rotation is set to 45, so it moves up and to the left at the set 45 degree angle. In other words: you're successfully rotating the probe in the A-P axis in the first image, but you can't see it because it's pointed straight down. Does that clear that up?

**Comment by RobertoDF** [comment]
I see but with this behaviour I can't simulate a probe that has only M-L tilt. To have M-L tilt I'm forced to tilt the probe also in A-P.

**Comment by petersaj** [comment]
Like this pictured below? You can do any angle - it's just done using spherical coordinates because those are the angles you'd use when setting up your manipulator (the first angle is the angle of the manipulator relative to the mouse, the second angle is the angle of the probe axis on the manipulator)

![image](https://user-images.githubusercontent.com/17985056/95382441-8eb7b500-08e1-11eb-8363-5e0ad90c94aa.png)

**Comment by RobertoDF** [comment]
I get it now, thanks!

**Comment by JorritMontijn** [comment]
Maybe I'm dimwitted, but I find the probe angles very counterintuitive. I expect that when I start the program I can change the ML angle with left/right and the AP angle with forward/back; instead I first have to rotate the probe to -90/+90 before I get behavior that would even start resemble what I expect. In general I don't see the benefit of being able to change the probe angle without actually changing the probe's angle. I think you guys have built a fantastic tool and I'm very happy that you shared it freely, but it would make me incredibly happy if you would add an option to make the probe angles absolute in cartesian space.

**Comment by petersaj** [comment]
I see that it's probably more intuitive/easier to change the angle by x/y coordinates of the bottom of the trajectory rather than the manipulator angles - I've updated it to do this, try it out and let me know how you like it. @RobertoDF this is the behavior I think you originally expected, you might like it more now.

Note: it converts the angle to still report the same manipulator angles along the top since these are what you need to actually set up your manipulator (angle of manipulator relative to mouse & angle of probe on manipulator)

**Comment by JorritMontijn** [comment]
This is great, thanks a lot for your quick modification!
